version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-30  # Choose the Android API level you need

    working_directory: ~/project

    steps:
      - checkout

      # Download and install dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Build and run tests
      - run:
          name: Build and Run Tests
          command: ./gradlew build connectedCheck

workflows:
  version: 2
  build:
    jobs:
      - build
